inventory/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('categories/', CategoryList.as_view(), name='category_list'),
    # ... other category URLs ...
    path('products/', ProductList.as_view(), name='product_list'),
    # ... other product URLs ...
    path('product_attachments/', ProductAttachmentList.as_view(), name='attachment_list'),
    path('products/<slug:slug>/', product_detail, name='product_detail'),
]

inventory_mgmt/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
    path('', include('storefront.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storefront/urls.py
from django.urls import path
from .views import *

app_name = 'storefront'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', custom_logout, name='logout'),
    path('', home, name="home"),
    path('p/<slug:product_slug>/', product_view, name='product_view'),
    # Add other URLs for your storefront
]

storefront/models.py
from django.db import models
import uuid
# Create your models here.
class BannerAdvert(models.Model):
    id = models.UUIDField(
        primary_key = True,
        default = uuid.uuid4,
        editable = False
    )

storefront/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit
from customer_relations.models import Customer

class UserLoginForm(forms.Form):
    username_or_email_or_phone = forms.CharField(label='Username or Email or Phone')
    password = forms.CharField(widget=forms.PasswordInput())

class UserRegistrationForm(UserCreationForm):
    # Additional fields from the Customer model
    phone_number = forms.IntegerField(label=None)
    phone_number_cc = forms.IntegerField(initial=91)
    email = forms.CharField(label='Email', max_length=201, required=False)  # Allow empty email field

    class Meta:
        model = User
        fields = [
                    'first_name',
                    'last_name',
                    'username',
                    'email',
                    'phone_number_cc',
                    'phone_number',
                    'password1',
                    'password2'
                ]

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        # Add Customer model fields to the form
        self.fields['phone_number_cc'].required = True
        self.fields['phone_number'].required = True
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Div(
                Div('first_name', css_class='mb-3'),
                Div('last_name', css_class='mb-3'),
                Div('username', css_class='mb-3'),
                Div('phone_number_cc', 'phone_number', css_class='mb-3 flex space-x-4'),
                Div('email', css_class='mb-3'),
                Div('password1', css_class='mb-3'),
                Div('password2', css_class='mb-3'),
                css_class='grid grid-cols-2 gap-4'
            ),
            Submit('submit', 'Register', css_class='btn btn-primary')
        )

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

            # Create a Customer instance associated with the user
            Customer.objects.create(
                user=user,
                phone_number_cc=self.cleaned_data['phone_number_cc'],
                phone_number=self.cleaned_data['phone_number'],
                email=self.cleaned_data['email']
            )

        return user

storefront/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import UserLoginForm
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from .forms import UserRegistrationForm
from customer_relations.models import Customer
from inventory.models import *
from inventory.serializer import *
import json

def home(request):
    return render(request, 'index.html')

def product_view(request, product_slug):
    product = Product.objects.get(slug=product_slug)
    attachments = ProductAttachment.objects.filter(publication=product)
    print(len(attachments))
    return render(request, 'product.html', {'product': product, 'attachments': attachments[0:], 'fa': attachments[0]})

def custom_logout(request):
    logout(request)
    # Redirect to the home page or any other desired page after logout
    return redirect('home')  # Replace 'home' with the desired redirect URL after logout

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('storefront:login')  # Change 'home' to your storefront home URL
    else:
        form = UserRegistrationForm()

    return render(request, 'register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username_or_email_or_phone = form.cleaned_data['username_or_email_or_phone']
            password = form.cleaned_data['password']

            if '@' in username_or_email_or_phone:
                user = authenticate(request, email=username_or_email_or_phone, password=password)
            else:
                # Check if the input is a phone number
                if username_or_email_or_phone.isdigit():
                    try:
                        # Assuming Customer model has a foreign key to the User model
                        customer = Customer.objects.get(phone_number=username_or_email_or_phone)
                        user = customer.user if customer else None
                    except Customer.DoesNotExist:
                        user = None
                else:
                    # Assume it's a username
                    user = authenticate(request, username=username_or_email_or_phone, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, 'Login successful!')
                return redirect('/')  # Replace 'home' with the desired redirect URL after login
            else:
                messages.error(request, 'Invalid login credentials.')

    else:
        form = UserLoginForm()

    return render(request, 'login.html', {'form': form})

storefront/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>
    {% block head%}
    {% endblock %}
  </head>
  <body>
    <header class="p-2 m-2 border-b-2 shadow rounded text-center justify-between flex">
      <nav class="p-1 w-full flex gap-4 text-inline text-center">
        <strong class="text-2xl">storefront</strong>
        <ul class="text-inline flex gap-4 w-full justify-end">
          <li> <a href="/">Home</a> </li>
          {% if user.is_authenticated %}
            <li><a href="/acccount/{{ user.username }}">{{ user.first_name}}'s Dashboard</a></li>
            <li><a href="/logout">Logout</a></li>
          {% else %}
            <li> <a href="/login">Login</a> </li>
            <li> <a href="/register">Register</a> </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    {% block content %}
    {% endblock %}
  </body>
</html>

storefront/templates/index.html
{% extends 'base.html' %}
{% block content %}

<script src="//unpkg.com/alpinejs" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.6.5/axios.min.js" integrity="sha512-TjBzDQIDnc6pWyeM1bhMnDxtWH0QpOXMcVooglXrali/Tj7W569/wd4E8EDjk1CwOAOPSJon1VfcEt1BI4xIrA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <div x-data="{ products: [] }" x-init="loadProducts">
<br><br>
    <strong class="text-4xl font-bold mb-4">Welcome to Our Store</strong>

    <!-- Product Listing -->
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
      <template x-for="product in products" :key="product.id">
        <a :href="'/p/'+product.slug" class=" group bg-white p-4 rounded shadow-md">
          <img :src="product.attachments[0].file" alt="Product Image" class="mb-4">
          <h3 class="text-xl font-semibold" x-text="product.name"></h3>
          <p class="text-gray-600" x-text="truncate(product.description, 100)"></p>
          <p class="mt-2 text-lg text-blue-500 font-bold" x-text="'Rs. ' + product.price"></p>
          <button class="group-hover:block hidden mt-4 bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-700">Add to Cart</button>
        </a>
      </template>
    </div>

    <script>
      function loadProducts() {
        axios.get('/inventory/products/')
          .then(response => {
            this.products = response.data;
          })
          .catch(error => {
            console.error('Error loading products:', error);
          });
      }
      function truncate(text, length) {
        return text.length > length ? text.slice(0, length) + '...' : text;
      }
    </script>

  </div>
{% endblock %}

storefront/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <section class="min-h-screen flex items-center justify-center">
    <div class="bg-white shadow-md p-8 rounded-md">
      <h2 class="text-2xl font-semibold mb-6">User Login</h2>
      <form method="post" action="{% url 'storefront:login' %}" class="grid grid-cols-1 gap-4">
        {% csrf_token %}
        <div class="mb-3">
          {{ form.username_or_email_or_phone|as_crispy_field }}
        </div>
        <div class="mb-3">
          {{ form.password|as_crispy_field }}
        </div>
        <button type="submit" class="bg-red-600 hover:bg-red-800 transition text-white py-2 px-4 rounded">Login</button>
      </form>
    </div>
  </section>
{% endblock %}

storefront/templates/product.html
{% extends 'base.html' %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block head %}
<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"
/>
{% endblock %}
{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/11.0.5/swiper-bundle.min.js" integrity="sha512-Ysw1DcK1P+uYLqprEAzNQJP+J4hTx4t/3X2nbVwszao8wD+9afLjBQYjz7Uk4ADP+Er++mJoScI42ueGtQOzEA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<div class="grid lg:grid-cols-2 gap-6 lg:gap-12 items-start max-w-6xl px-4 mx-auto py-6" x-data="" x-init="">
  <div class="grid md:grid-cols-5 gap-3 items-start">
    <div data-fancybox="product" href="/media/{{ fa.file }}" class="md:col-span-4">
      <img
          src="/media/{{ fa.file }}"
          alt="{{ fa.file_name }}"
        width="600"
        height="900"
        class="aspect-[2/3] object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
      />
    </div>
    <div class="hidden md:flex flex-col gap-3 items-start">
      {% if attachments|length > 1 %}
      {% for x in attachments %}
      <a data-fancybox="product" href="/media/{{ x.file }}"  class="border hover:border-gray-900 rounded-lg overflow-hidden transition-colors dark:hover:border-gray-50">
        <img
            src="/media/{{ x.file }}"
            alt="{{ x.file_name }}"
          width="100"
          height="120"
          class="aspect-[5/6] object-cover"
        />
        <span class="sr-only">{{ x.file_name }}</span>
      </a>
      {% endfor %}
      {% endif %}
    </div>
  </div>
  <script>
    Fancybox.bind("[data-fancybox]", {
  // Your custom options
});
  </script>
  <div class="grid gap-4 md:gap-10 items-start">
    <div class="grid gap-4">
      <h1 class="font-bold text-3xl lg:text-4xl" x-text="">{{ product.name }}</h1>
      <div class="flex items-center gap-4">
        <div class="flex items-center gap-0.5">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="w-5 h-5 fill-primary"
          >
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
          </svg>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="w-5 h-5 fill-primary"
          >
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
          </svg>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="w-5 h-5 fill-primary"
          >
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
          </svg>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="w-5 h-5 fill-muted stroke-muted-foreground"
          >
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
          </svg>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="w-5 h-5 fill-muted stroke-muted-foreground"
          >
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
          </svg>
        </div>
        <div class="text-4xl font-bold ml-auto" x-text="">Rs. {{ product.price }}</div>
      </div>
    </div>
    <form class="grid grid-cols-2 gap-4 md:gap-10">
      <button class="inline-flex items-center justify-center whitespace-nowrap font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-red-400 text-primary-foreground hover:bg-red-500 h-11 rounded-md px-8">
        <i class="fa-solid fa-cart-shopping"></i>
        &nbsp;
        Add to cart
      </button>
      <style>
        .wa-btn {
          background: #0BC44B;
        }
        .wa-btn:hover {
          background: #075E54;
          color: white;
        }
      </style>
      <button class="inline-flex items-center justify-center whitespace-nowrap font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 text-primary-foreground h-11 rounded-md px-8 wa-btn">
        <i class="fa-brands fa-whatsapp"></i>
        &nbsp;
        Contact Seller
      </button>
      <button class="inline-flex items-center justify-center whitespace-nowrap font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-teal-300 text-primary-foreground hover:bg-teal-400 h-11 rounded-md px-8">
        <i class="fa-solid fa-bag-shopping"></i>
        &nbsp;
        Buy Now
      </button>
      <button class="inline-flex items-center justify-center whitespace-nowrap font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-pink-300 text-primary-foreground hover:bg-pink-400 h-11 rounded-md px-8">
        <i class="fa-solid fa-share"></i>
        &nbsp;
        Refer a Friend
      </button>
    </form>
    <div class="grid gap-4">
      <h2 class="font-bold text-2xl">Product Details</h2>
      <p x-text="">
        {{ product.description }}
      </p>
    </div>
    <div class="grid gap-4">
      <h2 class="font-bold text-2xl">Customer Reviews</h2>
      <div class="grid gap-2">
        <p>No reviews for this Product yet</p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

storefront/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<section class="min-h-screen flex items-center justify-center">
  <div class="bg-white shadow-md p-8 rounded-md">
  <h2 class="mb-3 text-2xl">User Registration</h2>
  <div class="container">
    <form method="post" action="{% url 'storefront:register' %}">
      {% csrf_token %}
      <div class="gap-4 mb-4">
        <div class="mb-3">
          {{ form.first_name|as_crispy_field }}
        </div>
        <div class="mb-3">
          {{ form.last_name|as_crispy_field }}
        </div>
        <div class="mb-3">
          {{ form.username|as_crispy_field }}
        </div>
        <div class="mb-3 flex space-x-4">
          {{ form.phone_number_cc|as_crispy_field }}
          {{ form.phone_number|as_crispy_field }}
        </div>
        <div class="mb-3">
          {{ form.email|as_crispy_field }}
        </div>
        <div class="mb-3">
          {{ form.password1|as_crispy_field }}
        </div>
        <div class="mb-3">
          {{ form.password2|as_crispy_field }}
        </div>
      </div>
      <button type="submit" class="bg-red-600 hover:bg-red-800 p-2 rounded transition text-white">Register</button>
    </form>
  </div>
  </div>
</section>
{% endblock %}